export const ADMIN_COURSES_FETCHED = "ADMIN_COURSES_FETCHED";
export const ADMIN_ENROLLMENTS_FETCHED = "ADMIN_ENROLLMENTS_FETCHED";
export const ADMINS_FETCHED = "ADMINS_FETCHED";
export const LOADING_STARTED = "LOADING_STARTED";
export const LOADING_STOPPED = "LOADING_STOPPED";
export const COORDINATORS_FETCHED = "COODINATORS_FETCHED";
export const USERS_FETCHED = "USERS_FETCHED";
export const USERS_SEARCHED = "USERS_SEARCHED";

